apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  secretName: tls
  privateKey:
      rotationPolicy: Always
  dnsNames:
    - 'tanzu.example.com'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer